name: Check PR to develop

on:
  pull_request:
    branches:
      - develop
    paths:
      - .github/workflows/develop-build.yml
      - package-lock.json
      - package.json
      - src/**
      - tsconfig.json

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    container:
      image: docker://node:14
      volumes:
        - ${{ github.workspace }}:/build
      options: --workdir /build
    steps:
      # checkout
      - name: Checkout code
        uses: actions/checkout@v2
      # initialize node cache
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node_modules-${{ github.sha }}
          restore-keys: ${{ runner.os }}-node_modules-
      # npm install
      - name: Install dependencies
        run: npm i

  lint:
    name: Run linting
    needs: install
    runs-on: ubuntu-latest
    container:
      image: docker://node:14
      volumes:
        - ${{ github.workspace }}:/build
      options: --workdir /build
    steps:
      # checkout
      - name: Checkout code
        uses: actions/checkout@v2
      # initialize cache
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node_modules-${{ github.sha }}
          restore-keys: ${{ runner.os }}-node_modules-
      # lint
      - name: Run linting
        run: npx eslint --ext .ts src

  test:
    name: Run tests
    needs: install
    runs-on: ubuntu-latest
    container:
      image: docker://node:14
      volumes:
        - ${{ github.workspace }}:/build
      options:
        workdir: /build
    steps:
      # checkout
      - name: Checkout code
        uses: actions/checkout@v2
      # restore node cache
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node_modules-${{ github.sha }}
          restore-keys: ${{ runner.os }}-node_modules-
      # test
      - name: Run linting
        run: npm run test
